const canvas = document.getElementById('graph');
const ctx = canvas.getContext('2d');
const container = document.getElementById('graph-container');
const eqList = document.getElementById('eq-list');
const promptInput = document.getElementById('ai-prompt');
const generateBtn = document.getElementById('generate-btn');
const statusText = document.getElementById('ai-status');

const colors = ['#c74440', '#2d70b3', '#388c46', '#6042a6', '#fa7e19', '#000000'];
let equations = [];

let scale = 50;
let offsetX = 0;
let offsetY = 0;

// --- Event Listener for the Enter Key ---
promptInput.addEventListener('keypress', function (e) {
    if (e.key === 'Enter') {
        e.preventDefault();
        generateAiShape();
    }
});

function resizeCanvas() {
    canvas.width = container.clientWidth;
    canvas.height = container.clientHeight;
    if (offsetX === 0 && offsetY === 0) {
        offsetX = canvas.width / 2;
        offsetY = canvas.height / 2;
    }
    draw();
}
window.addEventListener('resize', resizeCanvas);

function addEquation(initialMath = '') {
    const id = Date.now();
    const color = colors[equations.length % colors.length];

    const row = document.createElement('div');
    row.className = 'equation-row';
    row.innerHTML = `
                <div class="color-dot" style="background-color: ${color};"></div>
                <input type="text" class="math-input" placeholder="e.g. x^2 or sin(x)" value="${initialMath}">
            `;

    const input = row.querySelector('.math-input');
    input.addEventListener('input', draw);

    eqList.appendChild(row);
    equations.push({ id, element: input, color });

    input.focus();
    draw();
}

// Math Parser
function parseMathText(expr) {
    let parsed = expr.toLowerCase()
        .replace(/\s+/g, '')
        .replace(/(\d)([xX\(a-zA-Z])/g, '$1*$2')
        .replace(/([xX\)])(\d)/g, '$1*$2')
        .replace(/\^/g, '**')
        .replace(/pi|π/g, 'Math.PI')
        .replace(/\be\b/g, 'Math.E')
        .replace(/\babs\b/g, 'Math.abs')
        .replace(/\bacos\b/g, 'Math.acos')
        .replace(/\basin\b/g, 'Math.asin')
        .replace(/\batan\b/g, 'Math.atan')
        .replace(/\bsin\b/g, 'Math.sin')
        .replace(/\bcos\b/g, 'Math.cos')
        .replace(/\btan\b/g, 'Math.tan')
        .replace(/\bsqrt\b/g, 'Math.sqrt')
        .replace(/\blog\b/g, 'Math.log10')
        .replace(/\bln\b/g, 'Math.log');
    return parsed;
}

// --- REAL AI GENERATION LOGIC WITH PUTER.JS ---
async function generateAiShape() {
    const prompt = promptInput.value.trim();
    if (!prompt) return;

    // UI Loading State
    generateBtn.disabled = true;
    generateBtn.innerText = "Thinking...";
    statusText.innerText = "Asking AI to calculate formulas...";
    statusText.style.color = "#8e44ad";

    try {
        const systemInstruction = `You are a mathematical graphing assistant. The user wants to draw: "${prompt}". 
                You must return ONLY a raw JSON array of strings containing mathematical formulas in terms of x. 
                Do not include y=. Do not include markdown code blocks. Just the array.
                Only use standard arithmetic and these functions: sin, cos, tan, sqrt, abs, acos, asin, atan, log, ln, e, pi. 
                Use x as the variable. Example output: ["sqrt(25-x^2)", "-sqrt(25-x^2)"]`;

        // Call the Puter.js AI SDK (using Gemini Flash)
        const response = await puter.ai.chat([
            { role: "system", content: systemInstruction },
            { role: "user", content: prompt }
        ], { model: "google/gemini-3.5-flash" });

        // Extract the content from the response
        let aiText = response.message.content;

        // Clean up any markdown formatting the AI might sneak in
        aiText = aiText.replace(/```json/g, '').replace(/```/g, '').trim();

        const newEquations = JSON.parse(aiText);

        // Clear current UI
        eqList.innerHTML = '';
        equations = [];

        // Add the new equations generated by the AI
        newEquations.forEach(eq => addEquation(eq));

        // Reset viewport
        scale = 50;
        offsetX = canvas.width / 2;
        offsetY = canvas.height / 2;
        draw();

        statusText.innerText = "Success! Shape generated.";
        statusText.style.color = "#27ae60";

    } catch (error) {
        console.error(error);
        statusText.innerText = "AI Error: Could not generate shape. Try rephrasing.";
        statusText.style.color = "#e74c3c";
    } finally {
        // Reset UI
        generateBtn.disabled = false;
        generateBtn.innerText = "Generate";
    }
}

// Render Loop
function draw() {
    ctx.clearRect(0, 0, canvas.width, canvas.height);

    // Grid
    ctx.lineWidth = 1; ctx.strokeStyle = '#e0e0e0'; ctx.beginPath();
    let startX = (offsetX % scale) - scale;
    for (let x = startX; x < canvas.width; x += scale) { ctx.moveTo(x, 0); ctx.lineTo(x, canvas.height); }
    let startY = (offsetY % scale) - scale;
    for (let y = startY; y < canvas.height; y += scale) { ctx.moveTo(0, y); ctx.lineTo(canvas.width, y); }
    ctx.stroke();

    // Axes
    ctx.lineWidth = 2; ctx.strokeStyle = '#000000'; ctx.beginPath();
    if (offsetY >= 0 && offsetY <= canvas.height) { ctx.moveTo(0, offsetY); ctx.lineTo(canvas.width, offsetY); }
    if (offsetX >= 0 && offsetX <= canvas.width) { ctx.moveTo(offsetX, 0); ctx.lineTo(offsetX, canvas.height); }
    ctx.stroke();

    // Equations
    equations.forEach(eq => {
        const expr = eq.element.value;
        if (!expr || !expr.includes('x')) return;

        const parsedExpr = parseMathText(expr);

        let f;
        try {
            f = new Function('x', 'return ' + parsedExpr);
            f(0);
        } catch (e) { return; }

        ctx.beginPath();
        ctx.strokeStyle = eq.color;
        ctx.lineWidth = 2.5;

        let firstPoint = true;

        for (let px = 0; px <= canvas.width; px++) {
            let mathX = (px - offsetX) / scale;
            try {
                let mathY = f(mathX);
                let py = offsetY - (mathY * scale);

                if (isFinite(py)) {
                    if (firstPoint) {
                        ctx.moveTo(px, py);
                        firstPoint = false;
                    } else {
                        ctx.lineTo(px, py);
                    }
                } else {
                    firstPoint = true;
                }
            } catch (e) {
                firstPoint = true;
            }
        }
        ctx.stroke();
    });
}

// Pan and Zoom
let isDragging = false;
let lastMouseX, lastMouseY;

canvas.addEventListener('mousedown', (e) => { isDragging = true; lastMouseX = e.clientX; lastMouseY = e.clientY; });
window.addEventListener('mouseup', () => { isDragging = false; });
window.addEventListener('mousemove', (e) => {
    if (!isDragging) return;
    offsetX += e.clientX - lastMouseX; offsetY += e.clientY - lastMouseY;
    lastMouseX = e.clientX; lastMouseY = e.clientY;
    draw();
});

canvas.addEventListener('wheel', (e) => {
    e.preventDefault();
    const zoomFactor = e.deltaY < 0 ? 1.1 : 0.9;
    scale *= zoomFactor;
    const mouseX = e.clientX - canvas.getBoundingClientRect().left;
    const mouseY = e.clientY - canvas.getBoundingClientRect().top;
    offsetX = mouseX - (mouseX - offsetX) * zoomFactor;
    offsetY = mouseY - (mouseY - offsetY) * zoomFactor;
    draw();
});

resizeCanvas();
addEquation('x^2');